In [37]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score,KFold
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,StandardScaler,OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error
from sklearn.decomposition import PCA

In [38]:
df=pd.read_csv('gurgaon_properties_post_feature_selection_v2.csv')

In [39]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [40]:
df['furnishing_type'].value_counts()

furnishing_type
0.0    2349
1.0    1018
2.0     187
Name: count, dtype: int64

In [41]:
# 0 is unfurnished,
#  1 is furnished, 
# 2 is semi-furnished
df['furnishing_type']=df['furnishing_type'].replace({0.0:'unfurnished',1.0:'furnished',2.0:'semi-furnished'})

In [42]:
df.head(10)

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.00,0.0,0.0,unfurnished,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.00,1.0,0.0,unfurnished,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.00,0.0,0.0,unfurnished,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.00,1.0,0.0,furnished,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.00,0.0,1.0,unfurnished,High,Mid Floor
5,flat,gwal pahari,7.50,4.0,4.0,3+,New Property,4842.00,1.0,0.0,furnished,Low,High Floor
6,flat,sector 108,2.00,3.0,3.0,3+,Relatively New,2116.00,1.0,0.0,unfurnished,Medium,High Floor
7,flat,sector 102,1.90,3.0,4.0,3,Relatively New,1710.00,1.0,0.0,unfurnished,High,Mid Floor
8,house,sector 105,1.20,3.0,2.0,1,Old Property,1185.51,0.0,0.0,unfurnished,Low,Low Floor
9,house,sector 26,4.50,3.0,3.0,2,Moderately Old,1350.00,1.0,0.0,unfurnished,Medium,Low Floor

In [43]:
X=df.drop(columns=['price'])
y=df['price']

In [44]:
# Split the data into training and testing sets
y_transformed=np.log(y)

Ordinal encoding

In [ ]:
columns_to_encode=['property_type','sector','balcony','agePossession','firnishing_type','luxury_category','floor_category']

In [46]:
#create a column transformer for preprocessing
preprocessor=ColumnTransformer(
    transformers=[
        ('num',StandardScaler(),['area','bathrooms','bedrooms']),
        ('cat',OneHotEncoder(handle_unknown='ignore'),columns_to_encode)
    ],
    remainder='passthrough'
)

In [ ]:
#creating a pipeline for the model
pipeline=Pipeline([
    ('preprocessor',preprocessor),
    ('regressor',LinearRegression())
])

In [53]:
# KFord cross validation
Kford=KFold(n_splits=5,shuffle=True,random_state=42)
scores=cross_val_score(pipeline,X,y_transformed,cv=Kford,scoring='r2')

NameError: name 'pipeline' is not defined

In [55]:
scores.mean(),scores.std()

NameError: name 'scores' is not defined

In [57]:
X_train,X_test,y_train,y_test=train_test_split(X,y_transformed,test_size=0.2,random_state=42)

In [60]:
Pipeline.fit(X_train,y_train)

ValueError: A given column is not a column of the dataframe

In [61]:
y_pred=pipeline.predict(X_test)

NameError: name 'pipeline' is not defined